### ISSUE TITLE
Scam??

### ISSUE THREAD

**Issue by Wolf727** [luckycoinblu/luckycoinoro#1]
![image](https://user-images.githubusercontent.com/97886897/151275589-17a9936c-3360-46d4-b682-89e6478db2db.png)

**Comment by luckycoinblu** [comment]
Very informative content.

**Comment by Wolf727** [comment]
> Very informative content.

mining with 0 reward, this is new algo

**Comment by Wolf727** [comment]
proof-of-null

**Comment by luckycoinblu** [comment]
We do not need a large audience of miners. Moreover, we are not going to fight with the current laws of states where mining is already prohibited. Therefore, on block 43800, we set a mining reward of 0. And introduced a monthly incentive to do among members of our community who support the consensus of our network. Our coin can only be received by owning a masternode or buying directly on the exchange.

**Comment by Wolf727** [comment]
why do you need a coin at all then) zero decentralization) rename - this craft cannot be called a blockchain, it is no different from ordinary ones printed in a huge amount of money))))))

**Comment by luckycoinblu** [comment]
Comparing with ordinary coins that can be mined at a price of zero and wait in a year or two that will cost at least $ 10, then you are absolutely right. But knowing what is happening within the community, you would have a different opinion.
